// AUTO-GENERATED by scripts/generate-exercise-map.mjs
// Source: Free Exercise DB (https://github.com/yuhonas/free-exercise-db, CC0)
// Each pattern matches an exercise name; the first match wins. Each pattern
// resolves to 2-4 photos (both images for each slug = start/end of the movement).

export type ExerciseImageEntry = {
  pattern: RegExp;
  photos: string[];
};

const fdb = (slug: string, index: 0 | 1) =>
  `https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/${slug}/${index}.jpg`;

const u = (id: string) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1200&q=70`;

export const EXERCISE_IMAGE_MAP: ExerciseImageEntry[] = [
  { pattern: /d[ée]velopp[ée] couch[ée] halt[ée]res/i, photos: [fdb("Dumbbell_Bench_Press", 0), fdb("Dumbbell_Bench_Press", 1), fdb("Decline_Dumbbell_Bench_Press", 0), fdb("Decline_Dumbbell_Bench_Press", 1)] },
  { pattern: /d[ée]velopp[ée] couch[ée] barre/i, photos: [fdb("Barbell_Bench_Press_-_Medium_Grip", 0), fdb("Barbell_Bench_Press_-_Medium_Grip", 1), fdb("Bench_Press_-_Powerlifting", 0), fdb("Bench_Press_-_Powerlifting", 1)] },
  { pattern: /d[ée]velopp[ée] couch[ée] vitesse|d[ée]velopp[ée] couch[ée]/i, photos: [fdb("Barbell_Bench_Press_-_Medium_Grip", 0), fdb("Barbell_Bench_Press_-_Medium_Grip", 1), fdb("Dumbbell_Bench_Press", 0), fdb("Dumbbell_Bench_Press", 1)] },
  { pattern: /d[ée]velopp[ée] inclin[ée] machine|d[ée]velopp[ée] inclin[ée]/i, photos: [fdb("Incline_Dumbbell_Press", 0), fdb("Incline_Dumbbell_Press", 1), fdb("Barbell_Incline_Bench_Press_-_Medium_Grip", 0), fdb("Barbell_Incline_Bench_Press_-_Medium_Grip", 1)] },
  { pattern: /d[ée]velopp[ée] d[ée]clin/i, photos: [fdb("Decline_Dumbbell_Bench_Press", 0), fdb("Decline_Dumbbell_Bench_Press", 1), fdb("Decline_Barbell_Bench_Press", 0), fdb("Decline_Barbell_Bench_Press", 1)] },
  { pattern: /chest press|press machine/i, photos: [fdb("Leverage_Chest_Press", 0), fdb("Leverage_Chest_Press", 1), fdb("Cable_Chest_Press", 0), fdb("Cable_Chest_Press", 1)] },
  { pattern: /pec deck|reverse pec deck|butterfly/i, photos: [fdb("Butterfly", 0), fdb("Butterfly", 1), fdb("Reverse_Flyes", 0), fdb("Reverse_Flyes", 1)] },
  { pattern: /[ée]cart[ée] poulie|cable cross|crossover/i, photos: [fdb("Cable_Crossover", 0), fdb("Cable_Crossover", 1), fdb("Flat_Bench_Cable_Flyes", 0), fdb("Flat_Bench_Cable_Flyes", 1)] },
  { pattern: /[ée]cart[ée] halt[ée]res|dumbbell fly|fly halt[ée]res/i, photos: [fdb("Dumbbell_Flyes", 0), fdb("Dumbbell_Flyes", 1), fdb("Incline_Dumbbell_Flyes", 0), fdb("Incline_Dumbbell_Flyes", 1)] },
  { pattern: /pompes? piqu[ée]es?|pike push/i, photos: [fdb("Handstand_Push-Ups", 0), fdb("Handstand_Push-Ups", 1), fdb("Pushups", 0), fdb("Pushups", 1)] },
  { pattern: /pompes?|push.?up/i, photos: [fdb("Pushups", 0), fdb("Pushups", 1), fdb("Decline_Push-Up", 0), fdb("Decline_Push-Up", 1)] },
  { pattern: /d[ée]velopp[ée] militaire|military press/i, photos: [fdb("Standing_Military_Press", 0), fdb("Standing_Military_Press", 1), fdb("Seated_Barbell_Military_Press", 0), fdb("Seated_Barbell_Military_Press", 1)] },
  { pattern: /d[ée]velopp[ée] [ée]paules machine/i, photos: [fdb("Smith_Machine_Overhead_Shoulder_Press", 0), fdb("Smith_Machine_Overhead_Shoulder_Press", 1), fdb("Dumbbell_Shoulder_Press", 0), fdb("Dumbbell_Shoulder_Press", 1)] },
  { pattern: /d[ée]velopp[ée] [ée]paules|shoulder press|overhead press/i, photos: [fdb("Dumbbell_Shoulder_Press", 0), fdb("Dumbbell_Shoulder_Press", 1), fdb("Standing_Military_Press", 0), fdb("Standing_Military_Press", 1)] },
  { pattern: /[ée]l[ée]vations? lat[ée]rales? (poulie|c[aâ]ble)|cable lateral/i, photos: [fdb("Cable_Seated_Lateral_Raise", 0), fdb("Cable_Seated_Lateral_Raise", 1), fdb("Side_Lateral_Raise", 0), fdb("Side_Lateral_Raise", 1)] },
  { pattern: /[ée]l[ée]vations? lat[ée]rales?|lateral raise|side raise/i, photos: [fdb("Side_Lateral_Raise", 0), fdb("Side_Lateral_Raise", 1), fdb("Lateral_Raise_-_With_Bands", 0), fdb("Lateral_Raise_-_With_Bands", 1)] },
  { pattern: /arri[èe]re d[''’]?[ée]paule|reverse pec|reverse fly|rear delt/i, photos: [fdb("Reverse_Flyes", 0), fdb("Reverse_Flyes", 1), fdb("Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench", 0), fdb("Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench", 1)] },
  { pattern: /face pull/i, photos: [fdb("Face_Pull", 0), fdb("Face_Pull", 1), fdb("Face_Pull", 0), fdb("Face_Pull", 1)] },
  { pattern: /[ée]l[ée]vations? frontales?|front raise/i, photos: [fdb("Front_Dumbbell_Raise", 0), fdb("Front_Dumbbell_Raise", 1), fdb("Front_Plate_Raise", 0), fdb("Front_Plate_Raise", 1)] },
  { pattern: /thruster/i, photos: [fdb("Kettlebell_Thruster", 0), fdb("Kettlebell_Thruster", 1), fdb("Double_Kettlebell_Push_Press", 0), fdb("Double_Kettlebell_Push_Press", 1)] },
  { pattern: /triceps (corde|rope)|push.?down rope/i, photos: [fdb("Triceps_Pushdown_-_Rope_Attachment", 0), fdb("Triceps_Pushdown_-_Rope_Attachment", 1), fdb("Cable_Hammer_Curls_-_Rope_Attachment", 0), fdb("Cable_Hammer_Curls_-_Rope_Attachment", 1)] },
  { pattern: /triceps poulie|pushdown|tirage triceps/i, photos: [fdb("Triceps_Pushdown", 0), fdb("Triceps_Pushdown", 1), fdb("Triceps_Pushdown_-_V-Bar_Attachment", 0), fdb("Triceps_Pushdown_-_V-Bar_Attachment", 1)] },
  { pattern: /extension triceps halt[ée]re|kickback/i, photos: [fdb("Tricep_Dumbbell_Kickback", 0), fdb("Tricep_Dumbbell_Kickback", 1), fdb("Bent_Over_One-Arm_Long_Bar_Row", 0), fdb("Bent_Over_One-Arm_Long_Bar_Row", 1)] },
  { pattern: /dips sur banc|bench dips/i, photos: [fdb("Bench_Dips", 0), fdb("Bench_Dips", 1), fdb("Dips_-_Triceps_Version", 0), fdb("Dips_-_Triceps_Version", 1)] },
  { pattern: /dips/i, photos: [fdb("Dips_-_Triceps_Version", 0), fdb("Dips_-_Triceps_Version", 1), fdb("Dips_-_Chest_Version", 0), fdb("Dips_-_Chest_Version", 1)] },
  { pattern: /barre au front|skull crusher|french press/i, photos: [fdb("Cable_Lying_Triceps_Extension", 0), fdb("Cable_Lying_Triceps_Extension", 1), fdb("Decline_Close-Grip_Bench_To_Skull_Crusher", 0), fdb("Decline_Close-Grip_Bench_To_Skull_Crusher", 1)] },
  { pattern: /tractions? \(assist[ée]es?|tractions? assist|assisted pull/i, photos: [fdb("Band_Assisted_Pull-Up", 0), fdb("Band_Assisted_Pull-Up", 1), fdb("Pullups", 0), fdb("Pullups", 1)] },
  { pattern: /tractions?|pull.?up|chin.?up/i, photos: [fdb("Pullups", 0), fdb("Pullups", 1), fdb("Chin-Up", 0), fdb("Chin-Up", 1)] },
  { pattern: /tirage vertical prise neutre|underhand pulldown/i, photos: [fdb("Underhand_Cable_Pulldowns", 0), fdb("Underhand_Cable_Pulldowns", 1), fdb("Wide-Grip_Lat_Pulldown", 0), fdb("Wide-Grip_Lat_Pulldown", 1)] },
  { pattern: /tirage vertical|lat pulldown|pulldown/i, photos: [fdb("Wide-Grip_Lat_Pulldown", 0), fdb("Wide-Grip_Lat_Pulldown", 1), fdb("Underhand_Cable_Pulldowns", 0), fdb("Underhand_Cable_Pulldowns", 1)] },
  { pattern: /tirage [ée]lastique|band pull/i, photos: [fdb("Band_Pull_Apart", 0), fdb("Band_Pull_Apart", 1), fdb("Band_Assisted_Pull-Up", 0), fdb("Band_Assisted_Pull-Up", 1)] },
  { pattern: /rowing halt[ée]re un bras|one.?arm.*row|rowing 1 bras/i, photos: [fdb("One-Arm_Dumbbell_Row", 0), fdb("One-Arm_Dumbbell_Row", 1), fdb("T-Bar_Row_with_Handle", 0), fdb("T-Bar_Row_with_Handle", 1)] },
  { pattern: /rowing poitrine appuy[ée]e?|chest.?supported row/i, photos: [fdb("Bent_Over_Two-Dumbbell_Row", 0), fdb("Bent_Over_Two-Dumbbell_Row", 1), fdb("Bent_Over_Two-Arm_Long_Bar_Row", 0), fdb("Bent_Over_Two-Arm_Long_Bar_Row", 1)] },
  { pattern: /rowing poulie basse|cable row/i, photos: [fdb("Seated_Cable_Rows", 0), fdb("Seated_Cable_Rows", 1), fdb("Elevated_Cable_Rows", 0), fdb("Elevated_Cable_Rows", 1)] },
  { pattern: /rowing inversé|inverted row|tirage australien/i, photos: [fdb("Inverted_Row", 0), fdb("Inverted_Row", 1), fdb("Inverted_Row_with_Straps", 0), fdb("Inverted_Row_with_Straps", 1)] },
  { pattern: /rowing machine|machine row|tirage horizontal/i, photos: [fdb("Seated_Cable_Rows", 0), fdb("Seated_Cable_Rows", 1), fdb("Elevated_Cable_Rows", 0), fdb("Elevated_Cable_Rows", 1)] },
  { pattern: /rowing barre|bent.?over.*row|rowing buste/i, photos: [fdb("Bent_Over_Barbell_Row", 0), fdb("Bent_Over_Barbell_Row", 1), fdb("T-Bar_Row_with_Handle", 0), fdb("T-Bar_Row_with_Handle", 1)] },
  { pattern: /rowing/i, photos: [fdb("Seated_Cable_Rows", 0), fdb("Seated_Cable_Rows", 1), fdb("Bent_Over_Barbell_Row", 0), fdb("Bent_Over_Barbell_Row", 1)] },
  { pattern: /pullover.*bras tendus|straight.?arm pull/i, photos: [fdb("Rope_Straight-Arm_Pulldown", 0), fdb("Rope_Straight-Arm_Pulldown", 1), fdb("Decline_Dumbbell_Flyes", 0), fdb("Decline_Dumbbell_Flyes", 1)] },
  { pattern: /pullover/i, photos: [fdb("Rope_Straight-Arm_Pulldown", 0), fdb("Rope_Straight-Arm_Pulldown", 1), fdb("Bent-Arm_Dumbbell_Pullover", 0), fdb("Bent-Arm_Dumbbell_Pullover", 1)] },
  { pattern: /curl pupitre|curl inclin[ée]|preacher curl/i, photos: [fdb("Preacher_Curl", 0), fdb("Preacher_Curl", 1), fdb("Cable_Preacher_Curl", 0), fdb("Cable_Preacher_Curl", 1)] },
  { pattern: /curl c[aâ]ble|cable curl|curl poulie/i, photos: [fdb("Cable_Preacher_Curl", 0), fdb("Cable_Preacher_Curl", 1), fdb("Cable_Hammer_Curls_-_Rope_Attachment", 0), fdb("Cable_Hammer_Curls_-_Rope_Attachment", 1)] },
  { pattern: /curl halt[ée]res?|dumbbell curl/i, photos: [fdb("Dumbbell_Bicep_Curl", 0), fdb("Dumbbell_Bicep_Curl", 1), fdb("Hammer_Curls", 0), fdb("Hammer_Curls", 1)] },
  { pattern: /curl barre|barbell curl|biceps barre/i, photos: [fdb("Barbell_Curl", 0), fdb("Barbell_Curl", 1), fdb("EZ-Bar_Curl", 0), fdb("EZ-Bar_Curl", 1)] },
  { pattern: /curl|biceps/i, photos: [fdb("Dumbbell_Bicep_Curl", 0), fdb("Dumbbell_Bicep_Curl", 1), fdb("Barbell_Curl", 0), fdb("Barbell_Curl", 1)] },
  { pattern: /squat barre|barbell squat|back squat/i, photos: [fdb("Barbell_Squat", 0), fdb("Barbell_Squat", 1), fdb("Front_Barbell_Squat", 0), fdb("Front_Barbell_Squat", 1)] },
  { pattern: /goblet squat/i, photos: [fdb("Goblet_Squat", 0), fdb("Goblet_Squat", 1), fdb("Bodyweight_Squat", 0), fdb("Bodyweight_Squat", 1)] },
  { pattern: /squat poids du corps|bodyweight squat/i, photos: [fdb("Bodyweight_Squat", 0), fdb("Bodyweight_Squat", 1), fdb("Box_Squat", 0), fdb("Box_Squat", 1)] },
  { pattern: /hack squat/i, photos: [fdb("Hack_Squat", 0), fdb("Hack_Squat", 1), fdb("Smith_Machine_Squat", 0), fdb("Smith_Machine_Squat", 1)] },
  { pattern: /\bsquat\b/i, photos: [fdb("Barbell_Squat", 0), fdb("Barbell_Squat", 1), fdb("Bodyweight_Squat", 0), fdb("Bodyweight_Squat", 1)] },
  { pattern: /presse [aà] cuisses|leg press/i, photos: [fdb("Leg_Press", 0), fdb("Leg_Press", 1), fdb("Wide_Stance_Stiff_Legs", 0), fdb("Wide_Stance_Stiff_Legs", 1)] },
  { pattern: /soulev[ée] (de terre )?roumain|romanian deadlift|rdl/i, photos: [fdb("Romanian_Deadlift", 0), fdb("Romanian_Deadlift", 1), fdb("Stiff-Legged_Dumbbell_Deadlift", 0), fdb("Stiff-Legged_Dumbbell_Deadlift", 1)] },
  { pattern: /soulev[ée] de terre|deadlift/i, photos: [fdb("Barbell_Deadlift", 0), fdb("Barbell_Deadlift", 1), fdb("Sumo_Deadlift", 0), fdb("Sumo_Deadlift", 1)] },
  { pattern: /hip thrust/i, photos: [fdb("Barbell_Hip_Thrust", 0), fdb("Barbell_Hip_Thrust", 1), fdb("Barbell_Glute_Bridge", 0), fdb("Barbell_Glute_Bridge", 1)] },
  { pattern: /pont fessier|glute bridge/i, photos: [fdb("Barbell_Glute_Bridge", 0), fdb("Barbell_Glute_Bridge", 1), fdb("Hip_Lift_with_Band", 0), fdb("Hip_Lift_with_Band", 1)] },
  { pattern: /kettlebell swing/i, photos: [fdb("One-Arm_Kettlebell_Swings", 0), fdb("One-Arm_Kettlebell_Swings", 1), fdb("Two-Arm_Kettlebell_Clean", 0), fdb("Two-Arm_Kettlebell_Clean", 1)] },
  { pattern: /leg curl|ischio.?jambier/i, photos: [fdb("Lying_Leg_Curls", 0), fdb("Lying_Leg_Curls", 1), fdb("Seated_Leg_Curl", 0), fdb("Seated_Leg_Curl", 1)] },
  { pattern: /leg extension|quadriceps|extension cuisses?/i, photos: [fdb("Leg_Extensions", 0), fdb("Leg_Extensions", 1)] },
  { pattern: /fentes|lunges?/i, photos: [fdb("Dumbbell_Lunges", 0), fdb("Dumbbell_Lunges", 1), fdb("Bodyweight_Walking_Lunge", 0), fdb("Bodyweight_Walking_Lunge", 1)] },
  { pattern: /mollets? debout|standing calf/i, photos: [fdb("Standing_Calf_Raises", 0), fdb("Standing_Calf_Raises", 1), fdb("Calf_Press", 0), fdb("Calf_Press", 1)] },
  { pattern: /mollets?(sur marche)?|calf raise/i, photos: [fdb("Standing_Calf_Raises", 0), fdb("Standing_Calf_Raises", 1), fdb("Seated_Calf_Raise", 0), fdb("Seated_Calf_Raise", 1)] },
  { pattern: /dead bug/i, photos: [fdb("Dead_Bug", 0), fdb("Dead_Bug", 1), fdb("Flat_Bench_Lying_Leg_Raise", 0), fdb("Flat_Bench_Lying_Leg_Raise", 1)] },
  { pattern: /pallof press/i, photos: [fdb("Pallof_Press", 0), fdb("Pallof_Press", 1), fdb("Reverse_Cable_Curl", 0), fdb("Reverse_Cable_Curl", 1)] },
  { pattern: /gainage lat[ée]ral|side plank|side bridge/i, photos: [fdb("Side_Bridge", 0), fdb("Side_Bridge", 1), fdb("Plank", 0), fdb("Plank", 1)] },
  { pattern: /gainage|plank|planche/i, photos: [fdb("Plank", 0), fdb("Plank", 1), fdb("Side_Bridge", 0), fdb("Side_Bridge", 1)] },
  { pattern: /crunch poulie|cable crunch/i, photos: [fdb("Cable_Crunch", 0), fdb("Cable_Crunch", 1), fdb("Crunches", 0), fdb("Crunches", 1)] },
  { pattern: /crunch|abs|abdos|hollow|sit.?up/i, photos: [fdb("Crunches", 0), fdb("Crunches", 1), fdb("Air_Bike", 0), fdb("Air_Bike", 1)] },
  { pattern: /relev[ée]s? (de )?jambes|leg raise|hanging leg/i, photos: [fdb("Hanging_Leg_Raise", 0), fdb("Hanging_Leg_Raise", 1), fdb("Flat_Bench_Lying_Leg_Raise", 0), fdb("Flat_Bench_Lying_Leg_Raise", 1)] },
  { pattern: /farmer.?walk|farmer.?carry/i, photos: [fdb("Farmers_Walk", 0), fdb("Farmers_Walk", 1), fdb("Rickshaw_Carry", 0), fdb("Rickshaw_Carry", 1)] },
  { pattern: /suspension|grip hang/i, photos: [fdb("Hanging_Leg_Raise", 0), fdb("Hanging_Leg_Raise", 1)] },
  { pattern: /tapis inclin|incline walk/i, photos: [u("1538805060514-97d9cc17730c"), u("1591741535018-d042766c62eb"), u("1571902943202-3935a0a3a47a")] },
  { pattern: /marche soutenue|marche optionnelle|marche/i, photos: [u("1538805060514-97d9cc17730c"), u("1591741535018-d042766c62eb")] },
  { pattern: /v[ée]lo|cycling|spin/i, photos: [u("1534258936925-c58bed479fcb"), u("1591741535018-d042766c62eb"), u("1538805060514-97d9cc17730c")] },
  { pattern: /rameur/i, photos: [u("1574680096145-d05b474e2155"), u("1538805060514-97d9cc17730c"), u("1591741535018-d042766c62eb")] },
  { pattern: /elliptique|stairmaster/i, photos: [u("1538805060514-97d9cc17730c"), u("1591741535018-d042766c62eb")] },
  { pattern: /corde [aà] sauter|jump rope/i, photos: [fdb("Rope_Jumping", 0), fdb("Rope_Jumping", 1)] },
  { pattern: /cardio (intervalles|hiit|zone)|hiit|intervalles/i, photos: [u("1591741535018-d042766c62eb"), u("1538805060514-97d9cc17730c")] },
  { pattern: /cardio/i, photos: [u("1591741535018-d042766c62eb"), u("1538805060514-97d9cc17730c"), u("1534258936925-c58bed479fcb")] },
  { pattern: /mobilit[ée] hanches?/i, photos: [u("1518611012118-696072aa579a"), u("1545205597-3d9d02c29597")] },
  { pattern: /rotations? thoraciques?|t-spine/i, photos: [u("1545205597-3d9d02c29597"), u("1518611012118-696072aa579a")] },
  { pattern: /mobilit[ée]/i, photos: [u("1518611012118-696072aa579a"), u("1545205597-3d9d02c29597"), u("1506629082955-511b1aa562c8")] },
  { pattern: /respiration/i, photos: [u("1545205597-3d9d02c29597"), u("1518611012118-696072aa579a")] },
  { pattern: /[ée]tirement pectoraux|[ée]tirement (pectoraux|mur)/i, photos: [u("1518611012118-696072aa579a"), u("1545205597-3d9d02c29597")] },
  { pattern: /[ée]tirement|stretch|yoga/i, photos: [u("1518611012118-696072aa579a"), u("1545205597-3d9d02c29597"), u("1506629082955-511b1aa562c8")] }
];

export function getExerciseImages(exerciseName: string): string[] | null {
  for (const entry of EXERCISE_IMAGE_MAP) {
    if (entry.pattern.test(exerciseName)) return entry.photos;
  }
  return null;
}
